variables:
  DOCKER_IMAGENAME: "mitrjain1996/student-api-server"
  DOCKER_VERSION: "v3.0"

stages:
  - build

build_image:
  stage: build
  image: docker:24.0.7-cli
  services:
   - docker:24.0.7-dind
  variables:
   DOCKER_TLS_CERTDIR: "/certs"
  before_script:
   - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
   - cd ./backend/student-service/students/
   - docker build -t $DOCKER_IMAGENAME:$DOCKER_VERSION .
   - docker push $DOCKER_IMAGENAME:$DOCKER_VERSION