version: '1'
services:
  students-db:
    build:
      context: ../database/studentdb
      dockerfile: ./Dockerfile
    env_file: ./env-students-db
  
  students-api-server:
    build:
      context: ../backend/student-service/students
      dockerfile: ./Dockerfile
    depends_on:
      - students-db
    env_file: ./env-students-api-server
  
  nginx-router:
    ports:
      - 8081:8081
    build:
      context: ../nginx
      dockerfile: ./Dockerfile
    depends_on:
      - students-api-server