apiVersion: apps/v1
kind: Deployment
metadata:
  name: students-api-server-deployment
  labels:
    app: students-api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: students-api-server-pod
  template:
    metadata:
      labels:
        app: students-api-server-pod
    spec:
      containers:
      - name: students-api-server
        image: mitrjain1996/student-api-server:v3.0
        ports:
        - containerPort: 8080
        env:
          - name: DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: students-config
                key: students-db-url
          - name: DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: students-secret
                key: students-db-user
          - name: DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: students-secret
                key: students-db-password
          
---
apiVersion: v1
kind: Service
metadata:
  name: students-api-server-service
spec:
  type: NodePort
  selector:
    app: students-api-server-pod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32000
